### ISSUE TITLE
Unable to run this command

### ISSUE THREAD

**Issue by mberg2007** [prashcr/reddid#2]
michael@michael-laptop:~/Downloads/reddit$ reddid pics hot 5
/usr/bin/env: ‘node --harmony’: No such file or directory

I did create a symlink to /usr/bin/nodejs from a place in my path. So this works:

$ node
> .exit
$ 

Any ideas?

**Comment by prashcr** [comment]
Which node version are you on? Could you show me the output of  
  
```
node --version
```

**Comment by mberg2007** [comment]
Yes:

$ node --version
v4.2.6
$ 

Also I'm running Ubuntu, pretty standard setup:

$ uname -a
Linux michael-laptop 4.4.0-64-generic #85-Ubuntu SMP Mon Feb 20 11:50:30 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

**Comment by prashcr** [comment]
Thanks, I'll spin up an Ubuntu vm and see if I can reproduce

**Comment by mberg2007** [comment]
Did you have any luck reproducing this problem?

**Comment by prashcr** [comment]
Incredibly sorry for the late reply. I tried it and was able to reproduce the problem. It seems Linux does not support arguments in a shebang, TIL.

https://github.com/SpencerCDixon/redux-cli/issues/42
  
The reason I used `node --harmony` was that back when I wrote it I was using arrow functions that weren't part of the latest stable node version, so I had to pass the `--harmony` flag to enable experimental features such as arrow functions.  
  
Now we're well past that and I don't see the need for `--harmony` anymore so I removed it and pushed a new version, it should work now.

**Comment by mberg2007** [comment]
Hi, thanks for your answer. How do I update my installed version?

I tried doing the npm install again but it hasn't resolved the problem. Same issue as before with the "--harmony" no such file message.

**Comment by prashcr** [comment]
Try `npm update -g reddid`

**Comment by prashcr** [comment]
My bad, it seems I didn't push the update to npm. I just did that, let me know if it works. Either npm install or update should work.

**Comment by mberg2007** [comment]
I'm sorry to bother you again with this issue but there seems to be another problem now:

```
michael@michael-laptop:~$ sudo npm update -g reddid
/usr/local/bin/reddid -> /usr/local/lib/node_modules/reddid/cli.js
/usr/local/lib
└── reddid@3.0.0 

michael@michael-laptop:~$ cd temp/reddid/
michael@michael-laptop:~/temp/reddid$ reddid earthporn hot 3
/usr/local/lib/node_modules/reddid/cli.js:19
let [sub, cat, num, time] = cli.input
    ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

```

**Comment by mberg2007** [comment]
And just FYI: "earthporn" isn't some bizarre fetish, it's images from beautiful locations around the world :-) Some of those photos are amazingly beautiful, I hope to use reddid to collect a few to use for my screensaver.

**Comment by prashcr** [comment]
I'm an avid redditor myself, no worries 😄 
I think that means your version of node.js is too old. It should work on anything v6+

**Comment by mberg2007** [comment]
That solved it. Took a bit of research to find out how to do that with Ubuntu but I'm now running version 7.x of nodejs and reddid is working like a charm now. The first 50 images are already on my drive :-)

Thanks for your help!
